# AI_Kaihatsu/docker-compose.yml
version: '3'

services:
  ai_back:
    build: ./ai_back
    container_name: ai_back
    ports:
      - "8080:8080"

  ai_front:
    build: ./ai_front
    container_name: ai_front
    ports:
      - "3000:3000"
